name: Generate Snake

on:
  # Her 6 saatdə bir çalışır
  schedule:
    - cron: "0 */6 * * *"
  
  # Manuel tetikleme imkanı verir
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repo'yu klonla
      - uses: actions/checkout@v4

      # Yılan animasyonunu oluştur
      - uses: Platane/snk@v3
        with:
          github_user_name: SamirValiyev  # GitHub kullanıcı adını doğru yaz!
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # Git durumunu kontrol et (debug amaçlı)
      - name: Git Status (Debug)
        run: git status

      # Değişiklikleri output branch'ine gönder
      - name: Push changes to output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      # GitHub Pages'e deploy et (output branch'ten)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
